name: Test-build
on:
  push:
    branches: [develop,master]
  pull_request:
    branches: [develop,master]
jobs:
    test-build:
        runs-on: ubuntu-latest
        environment: Build
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Install SSH key
            uses: shimataro/ssh-key-action@v2
            with:
              key: ${{ secrets.SSH_READ_KEY_UTIL }}
              name: id_ed25519 # optional
              known_hosts: ${{ secrets.KNOWN_HOSTS }}
              if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

          - name: Install Python
            uses: actions/setup-python@v4
            with:
              python-version: 3.8

          - name: install/upgrade pip
            run: |
              python -m pip install --upgrade pip


          - name: Install Dependencies
            run: python -m pip install -r requirements.txt

          - name: Build
            run: |
              mkdir test-results
              python3 -m invoke test --junit --enforce-percent 92

          - name: Store test results as artifacts
            uses: actions/upload-artifact@v2
            with:
              name: store test results
              path: test-results

          - name: Style
            run: python3 -m invoke style

          - name: Lint
            run: python3 -m invoke lint --fail-under=9
